# TB: ANIMAL_INS 
# CL: ANIMAL_ID, ANIMAL_TYPE, DATETIME
# INTAKE_CONDITION, NAME, SEX_UPON_INTAKE
# 모든 동물의 아이디, 이름, 보호 시작일을 
# 이름 순으로 조회, 이름이 같으면 DATETIME 역순으로
SELECT ANIMAL_ID, NAME, DATETIME
FROM ANIMAL_INS
ORDER BY NAME, DATETIME DESC
