-- 코드를 입력하세요
SELECT ICECREAM_INFO.FLAVOR
FROM ICECREAM_INFO
LEFT JOIN FIRST_HALF ON FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
WHERE FIRST_HALF.TOTAL_ORDER > 3000 AND ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based'
